on: [push]

jobs:
  build:
    runs-on: macos-latest
    name: Microsoft 365 quick evaluation test
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy with ARM template
      id: deployarm
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.RESOURCE_GROUPNAME}}
        template: ./deploy/storage.template.json
        parameters: storageAccountType=Standard_LRS
    - run: echo ${{ steps.deployarm.outputs.deploymentId }}

    - name: ACAT get quick assessment
      uses: azure/microsoft-365-certification-quick-evaluation@v1
      with:
        report-name: 'test-0303-2'
        deployment-ids: '[
        "${{ steps.deployarm.outputs.deploymentId }}",
        "${{ steps.deploybicep.outputs.deploymentId}}" 
        ]'
