on: [push]

jobs:
  build:
    runs-on: macos-latest
    name: Microsoft 365 quick evaluation test
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy with bicep
      id: deploybicep
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.RESOURCE_GROUPNAME}}
        template: ./deploy/storage.bicep
        parameters: storageAccountType=Standard_LRS
    - run: echo ${{ steps.deploybicep.outputs.deploymentId }}

    - name: Deploy with ARM template
      id: deployarm1
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.RESOURCE_GROUPNAME}}
        template: ./deploy/storage.template.json
        parameters: storageAccountType=Standard_LRS
    - run: echo ${{ steps.deployarm.outputs.deploymentId }}

    - name: Deploy with ARM template
      id: deployarm2
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.RESOURCE_GROUPNAME}}
        template: ./deploy/keyvault.template.json
    - run: echo ${{ steps.deployarm.outputs.deploymentId }}

    - name: Deploy with ARM template
      id: deployarm3
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.RESOURCE_GROUPNAME}}
        template: ./deploy/vm.template.json
        parameters: virtualMachines_name=${{ vars.VIRTUALMACHINES_NAME }} disks_externalid=${{ vars.DISKS_EXTERNALID }} networkInterfaces_externalid=${{ vars.NETWORKINTERFACES_EXTERNALID }}
    - run: echo ${{ steps.deployarm.outputs.deploymentId }}

    - name: ACAT get quick assessment
      uses: azure/microsoft-365-certification-quick-evaluation@v1
      with:
        report-name: 'test-0306-01'
        deployment-ids: '[
        "${{ steps.deployarm.outputs.deploymentId }}",
        "${{ steps.deploybicep.outputs.deploymentId}}" 
        ]'
